export enum EAttributeType {
    /** 攻击力 */
    attack = 'attack',
    /** 防御力 */
    defense = 'defense',
    /** 血量 */
    hp = 'hp',
    /** 合奏精通 */
    resonanceMastery = 'resonanceMastery',
    /** 百分比生命值 */
    hpPercent = 'hpPercent',
    /** 百分比攻击力 */
    attackPercent = 'attackPercent',
    /** 暴击率 */
    criticalChance = 'criticalChance',
    /** 暴击伤害 */
    criticalDamage = 'criticalDamage',

    /** 火元素抗性 */
    fireRes = 'fireRes',
    /** 水元素抗性 */
    waterRes = 'waterRes',
    /** 风元素抗性 */
    windRes = 'windRes',
    /** 雷元素抗性 */
    thunderRes = 'thunderRes',
    /** 岩元素抗性 */
    rockRes = 'rockRes',
    /** 光元素抗性 */
    lightRes = 'lightRes',
    /** 冰元素抗性 */
    iceRes = 'iceRes',
    /** 暗元素抗性 */
    darkRes = 'darkRes',
    /** 幻元素抗性 */
    phantomRes = 'phantomRes',

    /** 火元素伤害加成 */
    fireDamageBonus = 'fireDamageBonus',
    /** 水元素伤害加成 */
    waterDamageBonus = 'waterDamageBonus',
    /** 风元素伤害加成 */
    windDamageBonus = 'windDamageBonus',
    /** 雷元素伤害加成 */
    thunderDamageBonus = 'thunderDamageBonus',
    /** 岩元素伤害加成 */
    rockDamageBonus = 'rockDamageBonus',
    /** 光元素伤害加成 */
    lightDamageBonus = 'lightDamageBonus',
    /** 冰元素伤害加成 */
    iceDamageBonus = 'iceDamageBonus',
    /** 暗元素伤害加成 */
    darkDamageBonus = 'darkDamageBonus',
    /** 幻元素伤害加成 */
    phantomDamageBonus = 'phantomDamageBonus',

    /** 全元素伤害加成 */
    allElementDamageBonus = 'allElementDamageBonus',
    /** 穿透率 */
    penetration = 'penetration',
    /** 治疗强度 */
    healPower = 'healPower',
    /** 吸血率 */
    lifeSteal = 'lifeSteal',
    /** 幸运 */
    luck = 'luck',
    /** 魅力 */
    charm = 'charm',
    /** 速度 */
    speed = 'speed',
    /** 共鸣效率 */
    resonanceEfficiency = 'resonanceEfficiency',
}
